name: Build and test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Alumina compiler
      working-directory: /tmp
      env:
        RELEASE: 1
      run: |
        npm install -g tree-sitter-cli
        git clone https://github.com/tibordp/alumina.git
        cd alumina
        RELEASE=1 make alumina-boot
        sudo RELEASE=1 make install
    - uses: actions/checkout@v2
    - name: Build timestamped
      run: make
    - name: Run tests
      run: make tests
